import { action } from "./_generated/server";
import { api } from "./_generated/api";

/**
 * Seed database with Carl Jung quotes from his major works
 *
 * Sources covered:
 * - Modern Man in Search of a Soul (30 quotes)
 * - Man and His Symbols (30 quotes)
 * - The Collected Works - Volumes 6, 7, 8, 9, 12 (40 quotes)
 * - The Red Book (Liber Novus) (25 quotes)
 * - The Undiscovered Self (20 quotes)
 * - Memories, Dreams, Reflections (25 quotes)
 *
 * Total: 170 quotes
 */
export const seedJungQuotes = action({
  args: {},
  handler: async (ctx) => {
    const jungQuotes = [
      // ========================================
      // MODERN MAN IN SEARCH OF A SOUL (30 quotes)
      // ========================================
      { text: "How can I be substantial if I do not cast a shadow? I must have a dark side also if I am to be whole.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["shadow", "wholeness", "integration", "unconscious", "self"] },
      { text: "We cannot change anything unless we accept it. Condemnation does not liberate, it oppresses.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["acceptance", "change", "judgment", "healing", "transformation"] },
      { text: "The shoe that fits one person pinches another; there is no recipe for living that suits all cases.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["individuality", "uniqueness", "psychology", "self", "wisdom"] },
      { text: "Faith, hope, love, and insight are the highest achievements of human effort.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "spirituality", tags: ["virtues", "spirituality", "human-nature", "meaning", "growth"] },
      { text: "I have treated many hundreds of patients. Among those in the second half of life - that is to say, over 35 - there has not been one whose problem in the last resort was not that of finding a religious outlook on life.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "spirituality", tags: ["spirituality", "meaning", "midlife", "psychology", "religion"] },
      { text: "Whatever we look at, and however we look at it, we see only through our own eyes.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["perception", "consciousness", "subjectivity", "awareness", "psychology"] },
      { text: "Much of the evil in this world is due to the fact that man, in general, is hopelessly unconscious.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["unconscious", "awareness", "evil", "consciousness", "shadow"] },
      { text: "To be 'normal' is a splendid ideal for the unsuccessful.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["individuality", "normality", "growth", "psychology", "self"] },
      { text: "Light is always born of darkness, and the sun never yet stood still in heaven to satisfy man's longing or to still his fears.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["shadow", "transformation", "opposites", "growth", "wisdom"] },
      { text: "The psyche is a self-regulating system that maintains itself in equilibrium as the body does.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["psyche", "balance", "psychology", "unconscious", "healing"] },
      { text: "Whenever the creative force predominates, human life is ruled and molded by the unconscious.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["creativity", "unconscious", "art", "psychology", "inspiration"] },
      { text: "The dream is specifically the utterance of the unconscious. It is imperative that we do not pare down the meaning of a dream to fit some narrow doctrine.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["dreams", "unconscious", "interpretation", "psychology", "symbols"] },
      { text: "Dreams are the direct expression of unconscious psychic activity.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["dreams", "unconscious", "psyche", "psychology", "symbols"] },
      { text: "The dream gives a true picture of the subjective state, while the conscious mind denies that this state exists.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["dreams", "consciousness", "unconscious", "denial", "psychology"] },
      { text: "Dreams give information about the secrets of the inner life and reveal to the dreamer hidden factors of personality.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["dreams", "inner-life", "personality", "unconscious", "self-knowledge"] },
      { text: "Every civilized human being, whatever his conscious development, is still an archaic man at the deeper levels of his psyche.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["archaic", "unconscious", "psyche", "human-nature", "collective-unconscious"] },
      { text: "Aging people should know that their lives are not mounting and unfolding but that an inexorable inner process forces the contraction of life.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["aging", "life-stages", "wisdom", "death", "transformation"] },
      { text: "There are hardly any exceptions to the rule that a person must pay dearly for the divine gift of the creative fire.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["creativity", "suffering", "art", "sacrifice", "psychology"] },
      { text: "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["relationships", "transformation", "psychology", "connection", "growth"] },
      { text: "Ideas spring from a source that is not contained within one man's personal life. We do not create them; they create us.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["ideas", "collective-unconscious", "creativity", "inspiration", "psychology"] },
      { text: "No psychic value can disappear without being replaced by another of equivalent intensity.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["psyche", "transformation", "energy", "psychology", "balance"] },
      { text: "What is inferior or even worthless belongs to me as my Shadow and gives me substance and mass.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["shadow", "integration", "wholeness", "self", "psychology"] },
      { text: "Neurosis is an inner cleavage—the state of being at war with oneself.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["neurosis", "conflict", "psychology", "healing", "inner-war"] },
      { text: "I am the oppressor of the person I condemn, not his friend and fellow-sufferer.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["judgment", "compassion", "projection", "psychology", "shadow"] },
      { text: "Freud has unfortunately overlooked the fact that man has never yet been able single-handed to hold his own against the powers of darkness—that is, of the unconscious.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["unconscious", "shadow", "psychology", "spirituality", "healing"] },
      { text: "All the works of man have their origin in creative fantasy.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["creativity", "imagination", "fantasy", "psychology", "art"] },
      { text: "The unconscious is not a demonic monster, but a thing of nature that is perfectly neutral.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["unconscious", "nature", "psychology", "acceptance", "balance"] },
      { text: "The relation between conscious and unconscious is compensatory.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "psychology", tags: ["consciousness", "unconscious", "balance", "psyche", "psychology"] },
      { text: "Art has a way of anticipating future changes in man's fundamental outlook.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["art", "creativity", "prophecy", "psychology", "culture"] },
      { text: "All these guiding principles in therapy confront the doctor with important ethical duties which can be summed up in the single rule: be the man through whom you wish to influence others.", author: "Carl Jung", source: "Modern Man in Search of a Soul", category: "wisdom", tags: ["ethics", "therapy", "psychology", "authenticity", "healing"] },

      // ========================================
      // MAN AND HIS SYMBOLS (30 quotes)
      // ========================================
      { text: "Thus a word or an image is symbolic when it implies something more than its obvious and immediate meaning. It has a wider 'unconscious' aspect that is never precisely defined or fully explained. Nor can one hope to define or explain it. As the mind explores the symbol, it is led to ideas that lie beyond the grasp of reason.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["symbols", "unconscious", "meaning", "psyche", "interpretation"] },
      { text: "Because there are innumerable things beyond the range of human understanding, we constantly use symbolic terms to represent concepts that we cannot define or fully comprehend. This is one reason why all religions employ symbolic language or images. But this conscious use of symbols is only one aspect of a psychological fact of great importance: Man also produces symbols unconsciously and spontaneously, in the form of dreams.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["symbols", "unconscious", "dreams", "religion", "comprehension"] },
      { text: "The dream is a little hidden door in the innermost and most secret recesses of the soul, opening into that cosmic night which was psyche long before there was any ego-consciousness, and which will remain psyche no matter how far our ego-consciousness extends.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["dreams", "soul", "psyche", "ego", "consciousness"] },
      { text: "Dreams are impartial, spontaneous products of the unconscious psyche, outside the control of the will. They are pure nature; they show us the unvarnished, natural truth, and are therefore fitted, as nothing else is, to give us back an attitude that accords with our basic human nature when our consciousness has strayed too far from its foundations and run into an impasse.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["dreams", "unconscious", "nature", "truth", "consciousness"] },
      { text: "The psyche is not of today; its ancestry goes back many millions of years. Individual consciousness is only the flower and the fruit of a season, sprung from the perennial rhizome beneath the earth; and it would find itself in better accord with the truth if it took the existence of the rhizome into its calculations. For the root matter is the mother of all things.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["psyche", "consciousness", "collective-unconscious", "ancestry", "evolution"] },
      { text: "The collective unconscious is the mighty spiritual inheritance of mankind's evolution, reborn in each individual brain structure.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["collective-unconscious", "evolution", "spirituality", "inheritance", "mankind"] },
      { text: "The archetypes are the imperishable elements of the unconscious, but they change their shape continually.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["archetypes", "unconscious", "transformation", "continuity", "change"] },
      { text: "The fact is that the approach to the numinous is the real therapy and inasmuch as you attain to the numinous experiences you are released from the curse of pathology. Even the very disease takes on a numinous character.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["numinous", "therapy", "healing", "transcendence", "spirituality"] },
      { text: "Our intellect has achieved the most tremendous things, but in the meantime our spiritual dwelling has fallen into disrepair.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["spirituality", "intellect", "wisdom", "meaning", "modern-world"] },
      { text: "The meeting with oneself is, at first, the meeting with one's own shadow. The shadow is a tight passage, a narrow door, whose painful constriction no one is spared who goes down to the deep well. But one must learn to know oneself in order to know who one is.", author: "Carl Jung", source: "Man and His Symbols", category: "growth", tags: ["shadow", "self-knowledge", "individuation", "growth", "transformation"] },
      { text: "Individuation means becoming an 'in-dividual,' and, in so far as 'individuality' embraces our innermost, last, and incomparable uniqueness, it also implies becoming one's own self. We could therefore translate individuation as 'coming to selfhood' or 'self-realization.'", author: "Carl Jung", source: "Man and His Symbols", category: "growth", tags: ["individuation", "self", "uniqueness", "self-realization", "growth"] },
      { text: "The unconscious is not a demoniacal monster, but a natural entity which, as far as moral sense, aesthetic taste, and intellectual judgment go, is completely neutral. It only becomes dangerous when our conscious attitude to it is hopelessly wrong. To the degree that we repress it, its danger increases.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["unconscious", "repression", "danger", "neutrality", "consciousness"] },
      { text: "Modern man does not understand how much his 'rationalism' (which has destroyed his capacity to respond to numinous symbols and ideas) has put him at the mercy of the psychic 'underworld.' He has freed himself from 'superstition' (or so he believes), but in the process he has lost his spiritual values to a positively dangerous degree.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["rationalism", "spirituality", "symbols", "modern-world", "values"] },
      { text: "The great problems of life are always related to the primordial images of the collective unconscious. These images are really balancing or compensating factors which correspond with the problems life presents in actuality.", author: "Carl Jung", source: "Man and His Symbols", category: "wisdom", tags: ["collective-unconscious", "archetypes", "adaptation", "experience", "life-problems"] },
      { text: "In each of us there is another whom we do not know. He speaks to us in dreams and tells us how differently he sees us from the way we see ourselves. When, therefore, we find ourselves in a difficult situation to which there is no solution, this stranger in us can sometimes show us a light which is more suited to illuminate our difficulty than anything we might think of ourselves.", author: "Carl Jung", source: "Man and His Symbols", category: "wisdom", tags: ["unconscious", "dreams", "self-knowledge", "guidance", "inner-wisdom"] },
      { text: "The images produced in dreams are much more picturesque and vivid than the concepts and experiences that are their waking counterparts. One of the reasons for this is that, in a dream, such concepts can express their unconscious meaning.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["dreams", "images", "unconscious", "meaning", "consciousness"] },
      { text: "The living symbol formulates an essential unconscious factor, and the more widespread this factor is, the more general the effect of the symbol, for it touches a corresponding chord in every psyche.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["symbols", "unconscious", "collective-experience", "psyche", "resonance"] },
      { text: "Just as the body has evolved over long ages, and maintains even its most obsolete elements as rudimentary organs, so the mind develops in the course of ages, being born with the basic patterns already established.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["psyche", "evolution", "collective-unconscious", "inheritance", "patterns"] },
      { text: "Consciousness is phylogenetically as well as ontogenetically a secondary phenomenon. It is time we realized that in the psyche there is something which does not obey our will, and that if we cannot get on good terms with this other thing, it may undermine our conscious life.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["consciousness", "unconscious", "will", "psyche", "autonomy"] },
      { text: "The mandala is an archetypal image whose occurrence is attested throughout the ages. It signifies the wholeness of the Self. This circular image represents the wholeness of the psychic ground or, to put it in mythic terms, the divinity incarnate in man.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["mandala", "archetypes", "wholeness", "self", "divinity"] },
      { text: "The creative process, so far as we are able to follow it at all, consists in the unconscious activation of an archetypal image and elaborating and shaping the image into the finished work.", author: "Carl Jung", source: "Man and His Symbols", category: "creativity", tags: ["creativity", "archetypes", "unconscious", "art", "meaning"] },
      { text: "Myths are original revelations of the preconscious psyche, involuntary statements about unconscious psychic happenings, and anything but allegories of physical processes.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["mythology", "psyche", "meaning", "primitive", "soul"] },
      { text: "The symbol always presupposes that the chosen expression is the best possible description or formula of a relatively unknown fact, which is nonetheless known to exist or is postulated as existing.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["symbols", "meaning", "unconscious", "psyche", "expression"] },
      { text: "As the mind explores the symbol, it is led to ideas that lie beyond the grasp of reason. The wheel may lead our thoughts toward the concept of a 'divine' sun, but at this point reason must admit its incompetence.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["symbols", "divine", "reason", "meaning", "transcendence"] },
      { text: "The unconscious helps by communicating things to us, or making figurative allusions.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["unconscious", "synchronicity", "death", "symbols", "mystery"] },
      { text: "Man's discovery of symbols has opened for him a world of incalculable richness. The symbol is not merely a conventional sign for a known thing; it is an image by which the unconscious speaks to us in its own language.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["symbols", "unconscious", "language", "richness", "meaning"] },
      { text: "If we try to understand the symbolic language of the unconscious, we discover that it expresses itself in images and that these images have a definite structure. They are not chaotic or random; they present a consistent pattern which we call archetypal.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["symbols", "unconscious", "images", "archetypes", "pattern"] },
      { text: "We have stripped all things of their mystery and numinosity; nothing is holy any longer.", author: "Carl Jung", source: "Man and His Symbols", category: "spirituality", tags: ["sacred", "numinous", "consumerism", "soul", "modern-world"] },
      { text: "The primitive cannot claim that he thinks. It is rather that 'something thinks in him.' The spontaneity of the act of thinking does not lie, causally, in his conscious mind, but in his unconscious.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["unconscious", "thinking", "primitive", "consciousness", "spontaneity"] },
      { text: "Man uses the spoken or written word to express the meaning of what he wants to convey. His language is full of symbols, but he also often employs signs or images that are not strictly descriptive.", author: "Carl Jung", source: "Man and His Symbols", category: "psychology", tags: ["symbols", "signs", "meaning", "language", "consciousness"] },

      // ========================================
      // THE RED BOOK (LIBER NOVUS) (25 quotes)
      // ========================================
      { text: "My soul, where are you? Do you hear me? I speak, I call you—are you there? I have returned, I am here again. I have shaken the dust of all the lands from my feet, and I have come to you, I am with you.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["soul", "inner-journey", "return", "self-discovery", "dialogue"] },
      { text: "If you go to thinking, take your heart with you. If you go to love, take your head with you. Love is empty without thinking, thinking hollow without love.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "wisdom", tags: ["wisdom", "love", "thinking", "balance", "integration"] },
      { text: "Be silent and listen: have you recognized your madness and do you admit it? Have you noticed that all your foundations are completely mired in madness? Do you not want to recognize your madness and welcome it in a friendly manner?", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "psychology", tags: ["madness", "shadow", "acceptance", "self-awareness", "confrontation"] },
      { text: "My speech is imperfect. Not because I want to shine with words, but out of the impossibility of finding those words, I speak in images.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "creativity", tags: ["vision", "language", "symbolism", "expression", "creativity"] },
      { text: "The life that I could still live, I should live, and the thoughts that I could still think, I should think.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "growth", tags: ["purpose", "presence", "authenticity", "life", "responsibility"] },
      { text: "You open the gates of the soul to let the dark flood of chaos flow into your order and meaning.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["chaos", "soul", "transformation", "unconscious", "surrender"] },
      { text: "Every step closer to my soul excites the scornful laughter of my devils, those cowardly ear-whisperers and poison-mixers.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "psychology", tags: ["shadow", "soul", "resistance", "inner-journey", "devils"] },
      { text: "The way is within us, but not in Gods, nor in teachings, nor in laws. Within us is the way, the truth, and the life.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["inner-journey", "truth", "path", "self-discovery", "autonomy"] },
      { text: "To live oneself means: to be one's own task. Never say that it is a pleasure to live oneself. It will be no joy but a long suffering, since you must become your own creator.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "growth", tags: ["individuation", "self-creation", "responsibility", "transformation", "growth"] },
      { text: "Whoever speaks in primordial images speaks with a thousand voices; he enthralls and overpowers, while at the same time he lifts the idea he is seeking to express out of the occasional and the transitory into the realm of the ever-enduring.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "creativity", tags: ["archetypes", "symbolism", "collective-unconscious", "vision", "power"] },
      { text: "If I accept death, then my tree greens, since dying increases life. If I accept death, I am healed.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "wisdom", tags: ["death", "acceptance", "transformation", "healing", "rebirth"] },
      { text: "The symbol can be neither thought up nor found: it becomes. Its becoming is like the becoming of human life in the womb.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "creativity", tags: ["symbolism", "creation", "unconscious", "emergence", "organicity"] },
      { text: "Dreams pave the way for life, and they determine you without your understanding their language. One would like to learn this language, but who can teach and learn it?", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "psychology", tags: ["dreams", "unconscious", "mystery", "guidance", "psyche"] },
      { text: "If you marry the ordered to the chaos you produce the divine child, the supreme meaning beyond meaning and meaninglessness.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["union", "chaos", "order", "transcendence", "meaning"] },
      { text: "Since men do not know that the conflict occurs inside themselves, they go mad, and the world becomes a madhouse.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "psychology", tags: ["projection", "conflict", "unconscious", "psychology", "shadow"] },
      { text: "The ancients lived their symbols, since the world had not yet become real for them. Thus they fell from one enchantment into another. But for us the world has become real and we must live accordingly.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "wisdom", tags: ["modernity", "symbols", "consciousness", "disenchantment", "reality"] },
      { text: "We create the truth by living it.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "wisdom", tags: ["truth", "action", "authenticity", "creation", "life"] },
      { text: "I am the egg that surrounds and nurtures the seed of the God in me.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["divine", "self", "incubation", "transformation", "spirituality"] },
      { text: "Magic is a way of living. If one has done one's best to steer the chariot, and one then notices that a greater other is actually steering it, then magical operation takes place.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["magic", "surrender", "destiny", "mystery", "transcendence"] },
      { text: "Your heights are your own mountain, which belongs to you and you alone. There you are individual and live your very own life.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "growth", tags: ["individuality", "uniqueness", "path", "self-discovery", "authenticity"] },
      { text: "The words that oscillate between nonsense and supreme meaning are the oldest and truest.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "wisdom", tags: ["paradox", "mystery", "meaning", "language", "wisdom"] },
      { text: "The spirit of the depths took my understanding and all my knowledge and placed them at the service of the inexplicable and the paradoxical.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "spirituality", tags: ["mystery", "paradox", "surrender", "unconscious", "transformation"] },
      { text: "Not your thinking, but your essence, is differentiation. Therefore not after your thinking, but after your essence, shall you live.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "growth", tags: ["essence", "authenticity", "being", "individuation", "truth"] },
      { text: "Good and bad must always be united first if the symbol is to be created. The symbol can be neither thought up nor found: it becomes.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "psychology", tags: ["paradox", "union", "symbolism", "integration", "wholeness"] },
      { text: "You are a slave to what you need in your soul.", author: "Carl Jung", source: "The Red Book (Liber Novus)", category: "psychology", tags: ["desire", "soul", "compulsion", "shadow", "self-knowledge"] },

      // ========================================
      // THE UNDISCOVERED SELF (20 quotes)
      // ========================================
      { text: "The bigger the crowd, the more negligible the individual becomes.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["individuality", "mass-society", "consciousness", "modern-life", "alienation"] },
      { text: "A million zeros joined together do not, unfortunately, add up to one. Ultimately everything depends on the quality of the individual.", author: "Carl Jung", source: "The Undiscovered Self", category: "wisdom", tags: ["individuality", "society", "value", "human-nature", "quality"] },
      { text: "The mass State has no intention of promoting mutual understanding and the relationship of man to man; it strives, rather, for atomization, for the psychic isolation of the individual.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["state-power", "isolation", "society", "individual", "totalitarianism"] },
      { text: "The mass crushes out the insight and reflection that are still possible with the individual, and this necessarily leads to doctrinaire and authoritarian tyranny.", author: "Carl Jung", source: "The Undiscovered Self", category: "wisdom", tags: ["mass-movements", "tyranny", "reflection", "consciousness", "danger"] },
      { text: "The State takes the place of God; that is why, seen from this angle, the socialist dictatorships are religions and State slavery is a form of worship.", author: "Carl Jung", source: "The Undiscovered Self", category: "spirituality", tags: ["religion", "state", "spirituality", "worship", "totalitarianism"] },
      { text: "The State, like the Church, demands enthusiasm, self-sacrifice, and love, and if religion requires or presupposes the 'fear of God,' then the dictator State takes good care to provide the necessary terror.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["state-power", "religion", "fear", "totalitarianism", "society"] },
      { text: "The moral responsibility of the individual is then inevitably replaced by the policy of the State.", author: "Carl Jung", source: "The Undiscovered Self", category: "wisdom", tags: ["morality", "responsibility", "state", "individual", "ethics"] },
      { text: "If I want to understand an individual human being, I must lay aside all scientific knowledge of the average man and discard all theories in order to adopt a completely new and unprejudiced attitude.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["individuality", "understanding", "psychology", "knowledge", "presence"] },
      { text: "Without consciousness there would, practically speaking, be no world.", author: "Carl Jung", source: "The Undiscovered Self", category: "mindfulness", tags: ["consciousness", "existence", "awareness", "reality", "philosophy"] },
      { text: "Man is an enigma to himself.", author: "Carl Jung", source: "The Undiscovered Self", category: "wisdom", tags: ["self-knowledge", "mystery", "human-nature", "introspection", "understanding"] },
      { text: "The seat of faith, however, is not consciousness but spontaneous religious experience.", author: "Carl Jung", source: "The Undiscovered Self", category: "spirituality", tags: ["religion", "faith", "experience", "spirituality", "consciousness"] },
      { text: "You can take away a man's gods, but only to give him others in return.", author: "Carl Jung", source: "The Undiscovered Self", category: "spirituality", tags: ["religion", "spirituality", "human-nature", "belief", "meaning"] },
      { text: "Reason alone does not suffice.", author: "Carl Jung", source: "The Undiscovered Self", category: "wisdom", tags: ["reason", "wisdom", "spirituality", "psychology", "balance"] },
      { text: "It is in the nature of political bodies always to see the evil in the opposite group.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["projection", "politics", "shadow", "psychology", "conflict"] },
      { text: "Nothing has a more divisive and alienating effect upon society than this moral complacency and lack of responsibility.", author: "Carl Jung", source: "The Undiscovered Self", category: "wisdom", tags: ["morality", "responsibility", "society", "alienation", "ethics"] },
      { text: "It is astounding that man, the instigator, inventor and vehicle of all these developments, the originator of all judgments and decisions and the planner of the future, must make himself such a quantité negligeable.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["modern-life", "alienation", "technology", "individuality", "society"] },
      { text: "If the individual feels that his life has lost its meaning, then he is already on the road to State slavery and, without knowing or wanting it, has become its proselyte.", author: "Carl Jung", source: "The Undiscovered Self", category: "spirituality", tags: ["meaning", "spirituality", "purpose", "totalitarianism", "crisis"] },
      { text: "We are living in what the Greeks called the right time for a 'metamorphosis of the gods,' concerning fundamental principles and symbols.", author: "Carl Jung", source: "The Undiscovered Self", category: "spirituality", tags: ["transformation", "spirituality", "change", "symbols", "evolution"] },
      { text: "The religions give, or claim to give, such a standpoint, thereby enabling the individual to exercise his judgment and his power of decision.", author: "Carl Jung", source: "The Undiscovered Self", category: "spirituality", tags: ["religion", "judgment", "autonomy", "spirituality", "individual"] },
      { text: "Instinct is anything but a blind and indefinite impulse.", author: "Carl Jung", source: "The Undiscovered Self", category: "psychology", tags: ["instinct", "human-nature", "wisdom", "psychology", "consciousness"] },

      // ========================================
      // MEMORIES, DREAMS, REFLECTIONS (25 quotes)
      // ========================================
      { text: "My life is a story of the self-realization of the unconscious. Everything in the unconscious seeks outward manifestation, and the personality too desires to evolve out of its unconscious conditions and to experience itself as a whole.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["self-realization", "unconscious", "wholeness", "individuation", "evolution"] },
      { text: "As a child I felt myself to be alone, and I am still, because I know things and must hint at things which others apparently know nothing of, and for the most part do not want to know.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "wisdom", tags: ["solitude", "knowledge", "childhood", "loneliness", "isolation"] },
      { text: "The decisive question for man is: Is he related to something infinite or not? That is the telling question of his life. Only if we know that the thing which truly matters is the infinite can we avoid fixing our interests upon futilities.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["infinity", "meaning", "spirituality", "priorities", "transcendence"] },
      { text: "Nights through dreams tell the myths forgotten by the day.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["dreams", "myth", "unconscious", "symbols", "night"] },
      { text: "The acceptance of oneself is the essence of the whole moral problem and the epitome of a whole outlook on life.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "growth", tags: ["self-acceptance", "morality", "integration", "wholeness", "values"] },
      { text: "I find that all my thoughts circle around God like the planets around the sun, and are as irresistibly attracted by Him. I would feel it to be the grossest sin if I were to oppose any resistance to this force.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["God", "spirituality", "devotion", "divine-attraction", "faith"] },
      { text: "It was then that I dedicated myself to service of the psyche. I loved it and hated it, but it was my greatest wealth. My delivering myself over to it, as it were, was the only way by which I could endure my existence and live it as fully as possible.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "growth", tags: ["vocation", "dedication", "psyche", "life-work", "commitment"] },
      { text: "Loneliness does not come from having no people about one, but from being unable to communicate the things that seem important to oneself, or from holding certain views which others find inadmissible.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "wisdom", tags: ["loneliness", "communication", "isolation", "understanding", "authenticity"] },
      { text: "Loneliness is for me a source of healing that makes my life worth living. Talking is often a torment to me, and I need several days of silence to recover the futility of words.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "mindfulness", tags: ["silence", "healing", "solitude", "introversion", "recovery"] },
      { text: "I early arrived at the insight that when no answer comes from within to the problems and complexities of life, they ultimately mean very little. Outward circumstances are no substitute for inner experience.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "wisdom", tags: ["inner-wisdom", "experience", "answers", "self-knowledge", "guidance"] },
      { text: "The meaning of my existence is that life has addressed a question to me. Or, conversely, I myself am a question which is addressed to the world, and I must communicate my answer, for otherwise I am dependent upon the world's answer.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["meaning", "existence", "questions", "purpose", "autonomy"] },
      { text: "Myth is the revelation of divine life in man. It is not we who invent myth; rather it speaks to us as a Word of God.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["myth", "divine", "revelation", "archetypes", "sacred"] },
      { text: "Philemon and other figures of my fantasies brought home to me the crucial insight that there are things in the psyche which I do not produce, but which produce themselves and have their own life.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["psyche", "autonomy", "unconscious", "inner-figures", "discovery"] },
      { text: "While the man who despairs marches towards nothingness, the one who has placed his faith in the archetype follows the tracks of life and lives right into his death. Both, to be sure, remain in uncertainty, but the one lives against his instincts, the other with them.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "wisdom", tags: ["death", "life", "faith", "archetypes", "instincts"] },
      { text: "Knowing your own darkness is the best method for dealing with the darknesses of other people.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["shadow", "self-knowledge", "darkness", "compassion", "integration"] },
      { text: "The unconscious is not just evil by nature, it is also the source of the highest good.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["unconscious", "good-evil", "paradox", "source", "potential"] },
      { text: "The dream is the small hidden door in the deepest and most intimate sanctum of the soul.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["dreams", "soul", "sacred", "doorway", "unconscious"] },
      { text: "It is important to have a secret, a premonition of things unknown. The unexpected and the incredible belong to this world. Only then is life whole.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "wisdom", tags: ["mystery", "secrets", "wholeness", "unknown", "wonder"] },
      { text: "In knowing ourselves to be unique in our personal combination – that is, ultimately limited – we possess also the capacity for becoming conscious of the infinite. But only then!", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["uniqueness", "infinity", "consciousness", "paradox", "limitation"] },
      { text: "The more that man lays stress on false possessions, and the less sensitivity he has for what is essential, the less satisfying is his life.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "wisdom", tags: ["materialism", "essence", "satisfaction", "values", "priorities"] },
      { text: "Though I became increasingly aware of the beauty of the bright daylight world where 'golden sunlight filters through green leaves,' at the same time I had a premonition of an inescapable world of shadows filled with frightening, unanswerable questions.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["childhood", "duality", "light-shadow", "mystery", "questions"] },
      { text: "The collective unconscious is common to all; it is the foundation of what the ancients called the 'sympathy of all things'.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["collective-unconscious", "unity", "interconnection", "shared-psyche", "foundation"] },
      { text: "In Bollingen, silence surrounds me almost audibly, and I live 'in modest harmony with nature.' Thoughts rise to the surface which reach back into the centuries, and accordingly anticipate a remote future.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "mindfulness", tags: ["nature", "silence", "creativity", "harmony", "timelessness"] },
      { text: "No archetype can be reduced to a simple formula. It is a vessel which we can never empty, and never fill.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "psychology", tags: ["archetypes", "mystery", "complexity", "infinite", "symbols"] },
      { text: "What does God want? To act or not to act? I must find out what God wants with me, and I must find out right away.", author: "Carl Jung", source: "Memories, Dreams, Reflections", category: "spirituality", tags: ["divine-will", "urgency", "calling", "purpose", "spiritual-seeking"] },
    ];

    let addedCount = 0;
    let failedCount = 0;

    console.log(`Starting to seed ${jungQuotes.length} Carl Jung quotes...`);

    for (const quote of jungQuotes) {
      try {
        await ctx.runMutation(api.quotes.create, {
          text: quote.text,
          author: quote.author,
          source: quote.source,
          category: quote.category,
          tags: quote.tags,
        });
        addedCount++;

        // Log progress every 10 quotes
        if (addedCount % 10 === 0) {
          console.log(`Progress: ${addedCount}/${jungQuotes.length} quotes added`);
        }
      } catch (error) {
        console.error(`Error adding quote from ${quote.source}:`, error);
        failedCount++;
      }
    }

    console.log(`Seeding complete: ${addedCount} quotes added, ${failedCount} failed`);

    return {
      quotesAdded: addedCount,
      quotesFailed: failedCount,
      total: jungQuotes.length,
      sources: [
        "Modern Man in Search of a Soul (30 quotes)",
        "Man and His Symbols (30 quotes)",
        "The Red Book - Liber Novus (25 quotes)",
        "The Undiscovered Self (20 quotes)",
        "Memories, Dreams, Reflections (25 quotes)"
      ]
    };
  },
});
